### ISSUE TITLE
Build success but README.md not getting updated with new images.

### ISSUE THREAD

**Issue by Sohamsdays** [bongdevhq/profile-showcase#34]
**Describe the bug**
Build success but README.md not getting updated with images.

**To Reproduce**
1. Trigger github actions on a successful pull request

**Expected behavior**
New images with description should appear on the README.md

**Screenshots**
NA

**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
NA

**Additional context**
[Checkout this successful build which should have updated the readme markdown file ](https://github.com/bongdevhq/profile-showcase/actions/runs/6481128361)

**Comment by ItsRoy69** [comment]
Can work on this issue

**Comment by bongdev** [comment]
Hi @Sohamsdays , Thanks for pointing this out . We appreciate if you and @ItsRoy69 can collaborate to fix this. Marking this as 'Critical'

**Comment by bongdev** [comment]
This failed with following 

`File "/home/runner/work/profile-showcase/profile-showcase/.github/scripts/update_readme.py", line 20
    image = lines[2].split(":")[1].strip().replace("'", "")                location = lines[2].strip().split(":")[1].strip().replace("'",")
                                                                                                                                         ^
SyntaxError: unterminated string literal (detected at line 20)
Error: Process completed with exit code 1.
`

@ItsRoy69 @chiraagbanerjee

**Comment by chiraagbanerjee** [comment]
fixed the python script. Removed lines that was causing the error.

**Comment by chiraagbanerjee** [comment]
Run python .github/scripts/update_readme.py
Image atmajo.png is corrupted
Warning: File sarthakroy2002.md doesn't match the expected format. Skipping...
Image logo.jpg is corrupted
Warning: File default.md doesn't match the expected format. Skipping...
[main 83b1da7] Update README.md
 13 files changed, 66 insertions(+), 3 deletions(-)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request.        
To https://github.com/bongdevhq/profile-showcase
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/bongdevhq/profile-showcase'
@ItsRoy69 can you please check the yml, python script is running fine i have tasted it.
I think there are some permission related issue in yml, that's why changes are not getting reflected in the main branch of the repo.

**Comment by alokemajumder** [comment]
This is fixed .
